### ISSUE TITLE
Posts: increase spacing between subheads and paragraphs

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#31]
Seems a little tight

<img width="996" alt="screen shot 2017-06-26 at 2 52 13 pm" src="https://user-images.githubusercontent.com/5384728/27558208-22a335f8-5a82-11e7-9c0a-52c1c108b78a.png">

**Comment by jakewelchert** [comment]
1. Add **class='full-width'** to images
2. Update body.css and news-listing.css and we'll review again

**Comment by alexpgates** [comment]
@jakewelchert I _sorta_ did what you asked, and I think it worked out.

Line 14 of body.css:

`.single-body img.full-width, .single-body img.size-full {
	margin: 30px 0 50px;
}`

Instead of adding a filter on all the images in the_content() I decided to edit this CSS to attach those styles to `img.size-full` since this class is automatically applied to full-width images through the editor. 

The margins work now, but please double check.

If push comes to shove, I can add that filter to add that class to the images, but in this case I thought it would be easier and better to just utilize the class that's already there.

**Comment by justinkemerling** [comment]
Something wonky happened here. The body copy looks good though.

<img width="1258" alt="screen shot 2017-06-29 at 6 42 51 pm" src="https://user-images.githubusercontent.com/5384728/27715145-d98b4a38-5cfa-11e7-9ac3-b385be29247f.png">
