### ISSUE TITLE
Photo credit/caption

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/dcd#40]
@alexpgates

Added styling to the caption text under images. I've placed this in the **body.css** file and pushed to Github, but I believe you changed something on your end with the full-width image so maybe avoid an overwrite.

.wp-caption-text {
	margin-top: -45px;
	margin-bottom: 25px;
	font-size: 14px;
}

**Comment by jakewelchert** [comment]
I also edited another line of CSS in the **body.css** file for underlines under links: 

.single-body p a, .interior-body p a { text-decoration: underline;}

**Comment by alexpgates** [comment]
<img width="818" alt="screenshot 2017-06-30 12 34 28" src="https://user-images.githubusercontent.com/242736/27747377-7bd15f36-5d90-11e7-822a-df880bff3c44.png">

This got goofy. : |

**Comment by jakewelchert** [comment]
That image doesn't have the full-width class on it for some reason. I based the caption styles off of the image having a margin..so the caption has a negative margin to overwrite the image margins. Does that make sense?

**Comment by alexpgates** [comment]
@jakewelchert Dang. Okay. So, look back at this one:
https://github.com/jakewelchert/dcd/issues/31#issuecomment-312134116

Instead of adding the full-width class, I just applied the css from your full-width class to the .size-full class that is applied automatically in WP for images that are set to be full-sized.

I just edited the photo in the post (http://preview.douglascountydemocrats.com/2017/06/megan-hunt-declares-her-candidacy-for-the-nebraska-state-senate/) and now the caption works, but the image itself extends beyond the container.

Ideally, I'd like to avoid having to filter all the post content in order to apply classes. 

That said, the WP admin does have "advanced options" in images that allow you to apply a css class to an individual image. I can add some code to automatically make any new images take on that class when they are added. (https://stackoverflow.com/a/32901019/306359) 
That's probably the best approach. 

However, if we could edit .size-full to do everything .full-width does, then we wouldn't have to do it. 

I imagine Justin went in and set the manual height and width on that photo of Megan, which is fine - but I think it'd be easier for the DCDP team to just use the size-full on all images rather than having them go in and edit height and width.


Weird, I know. This one is tricky and confusing. Let me know if you have any questions or a preferred way to make this work.

**Comment by justinkemerling** [comment]
Yeah, that's what I did w/ Megan's. And yeah, easier for DCDP if they just used size-full. If it because of the caption, we can just not have a different size for it.

**Comment by jakewelchert** [comment]
@alexpgates

Okay, so we might be able to avoid all of this by simply changing the specificity of the image being called. Really, the images in the News layout are the only ones that need a top and bottom margin, and also might have caption text. So, instead of adding a class .full-width to an image to get top and bottom margins, we could just call all images in **.single-body** and have them use margin: 30px 0 50px.

This avoids having to have WordPress add a class when creating content. Let me know if I'm off here.

**Comment by alexpgates** [comment]
@jakewelchert @justinkemerling 
I applied that margin to all images inside .single-body, and also set a max-width of 100% on .wp-caption. Without that max-width, it was setting a width based on the image size and still causing the photo itself to extend beyond the post container.

Let me know if this is looking how you expect. I think it's great!

**Comment by justinkemerling** [comment]
Wonderful! Gold.
